---
- name: install docker & docker-compose
  hosts: local
  become: true
  tasks:
    # sudo apt-get update
    - name: Update apt packages
      apt:
        update_cache: yes
      tags:
        - docker

    # sudo apt-get install docker-ce=18.03.*
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      tags:
        - docker

    # sudo starting docker service
    - name: Start docker
      service: name=docker state=started

    # sudo apt-get install docker-compose=1.8.*
    - name: Install docker-compose
      apt:
        name: docker-compose
        state: present
        update_cache: yes
      tags:
        - docker